#define CLAW_OPEN_POWER 100
#define CLAW_CLOSE_POWER 100
#define CLAW_HOLD_POWER 50
#define USER_CONTROL_STATE 0
#define HOLD_POWER_STATE 1
#define LIFT_POWER 75
#define MOBILE_GOAL_POWER 100
#define MOBILE_GOAL_HOLD_POWER 20
